services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3005:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/images
      - ./icons:/app/icons
    environment:
      - PUID=1000
      - PGID=1000
      - PROXMOX_USERNAME=$PROXMOX_USERNAME
      - PROXMOX_TOKEN=$PROXMOX_TOKEN
    restart: unless-stopped