---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Machines:
    - Proxmox:
        href: [url]
        description: All machines
        icon: proxmox-light.png
        statusStyle: "basic"

- Apps:
    - Portainer:
        href: [url]
        description: Docker containers
        icon: portainer.png
        statusStyle: "basic"
        widget:
          type: portainer
          url: [url]
          env: 2
          key: key

    - Pterodactyl:
        href: [url]
        description: Game Servers
        icon: pterodactyl.png
        statusStyle: "basic"
        widget:
          type: pterodactyl
          url: [url]
          key: key

    - Uptime Kuma:
        href: [url]
        description: Status page
        icon: uptime-kuma.png
        statusStyle: "basic"
        widget:
          type: uptimekuma
          url: [url]
          slug: [slug]

    - Calendar:
        widget:
          type: calendar
          firstDayInWeek: monday # optional - defaults to monday
          view: monthly # optional - possible values monthly, agenda
          maxEvents: 10 # optional - defaults to 10
          showTime: true # optional - show time for event happening today - defaults to false
          timezone: Europe/Istanbul # optional and only when timezone is not detected properly (slightly slower performance) - force timezone for ical events (if it's the same - no change, if missing or different in ical - will be converted to this timezone)
