- logo:
    icon: shell-light.png

- openmeteo:
    label: Home # optional
    latitude: 0
    longitude: 0
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1

- resources:
    cpu: true
    memory: true
    disk: /dev/
    cputemp: true
    tempmin: 0 # optional, minimum cpu temp
    tempmax: 100 # optional, maximum cpu temp
    uptime: true
    units: imperial # only used by cpu temp
    refresh: 1000 # optional, in ms
    diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk

- datetime:
    locale: TR
    text_size: xl
    format:
      #dateStyle: short
      timeStyle: short
      hourCycle: h23
